export const partners = [
    { id: 1, category_id: [1], name: 'Jack Drink', logo: "https://via.placeholder.com/300x300" },
    { id: 2, category_id: [2, 5], name: 'Brabion Flowers', logo: "https://via.placeholder.com/300x300" },
    { id: 3, category_id: [3], name: 'Meat World', logo: "https://via.placeholder.com/300x300" },
    { id: 4, category_id: [4], name: 'Healthy Food Co.', logo: "https://via.placeholder.com/300x300" },
    { id: 5, category_id: [5], name: 'Wedding Bliss', logo: "https://via.placeholder.com/300x300" },
    { id: 6, category_id: [1, 4], name: 'Cool Beverages', logo: "https://via.placeholder.com/300x300" },
    { id: 7, category_id: [2, 3], name: 'Bloom & Meat', logo: "https://via.placeholder.com/300x300" },
    { id: 8, category_id: [3, 4], name: 'Grill & Eat', logo: "https://via.placeholder.com/300x300" },
    { id: 9, category_id: [1, 5], name: 'Elegant Drinks', logo: "https://via.placeholder.com/300x300" },
    { id: 10, category_id: [2], name: 'Fresh Flowers Co.', logo: "https://via.placeholder.com/300x300" },
    { id: 11, category_id: [4], name: 'Green Grocers', logo: "https://via.placeholder.com/300x300" },
    { id: 12, category_id: [3, 5], name: 'Carnivore Weddings', logo: "https://via.placeholder.com/300x300" },
    { id: 13, category_id: [2, 4], name: 'Petals & Plates', logo: "https://via.placeholder.com/300x300" },
    { id: 14, category_id: [1], name: 'Party Drinks', logo: "https://via.placeholder.com/300x300" },
    { id: 15, category_id: [5], name: 'Wedding Charm', logo: "https://via.placeholder.com/300x300" },
    { id: 16, category_id: [1, 3], name: 'Meaty Drinks', logo: "https://via.placeholder.com/300x300" },
    { id: 17, category_id: [4, 5], name: 'Banquet Experts', logo: "https://via.placeholder.com/300x300" },
    { id: 18, category_id: [2, 5], name: 'Romantic Blooms', logo: "https://via.placeholder.com/300x300" },
    { id: 19, category_id: [3], name: 'Prime Meats', logo: "https://via.placeholder.com/300x300" },
    { id: 20, category_id: [4], name: 'Healthy Eating', logo: "https://via.placeholder.com/300x300" },
    { id: 21, category_id: [1], name: 'Fizz Drinks', logo: "https://via.placeholder.com/300x300" },
    { id: 22, category_id: [2, 4], name: 'Flowers & Greens', logo: "https://via.placeholder.com/300x300" },
    { id: 23, category_id: [5], name: 'Wedding Boutique', logo: "https://via.placeholder.com/300x300" },
    { id: 24, category_id: [1, 4], name: 'Refresh Co.', logo: "https://via.placeholder.com/300x300" },
    { id: 25, category_id: [3, 5], name: 'Meat Fest Weddings', logo: "https://via.placeholder.com/300x300" },
    { id: 26, category_id: [2], name: 'Flower Heaven', logo: "https://via.placeholder.com/300x300" },
    { id: 27, category_id: [4], name: 'Organic Eats', logo: "https://via.placeholder.com/300x300" },
    { id: 28, category_id: [1, 3], name: 'Drinks & Deli', logo: "https://via.placeholder.com/300x300" },
    { id: 29, category_id: [5], name: 'Bridal Elegance', logo: "https://via.placeholder.com/300x300" },
    { id: 30, category_id: [2, 4], name: 'Bloom & Grow', logo: "https://via.placeholder.com/300x300" },
    { id: 31, category_id: [3, 4], name: 'Meat & More', logo: "https://via.placeholder.com/300x300" },
    { id: 32, category_id: [1, 5], name: 'Celebration Drinks', logo: "https://via.placeholder.com/300x300" },
    { id: 33, category_id: [2, 3], name: 'Floral Feast', logo: "https://via.placeholder.com/300x300" },
    { id: 34, category_id: [4, 5], name: 'Wedding Banquets', logo: "https://via.placeholder.com/300x300" },
    { id: 35, category_id: [1], name: 'Sparkling Beverages', logo: "https://via.placeholder.com/300x300" },
    { id: 36, category_id: [2], name: 'Flower Fantasy', logo: "https://via.placeholder.com/300x300" },
    { id: 37, category_id: [3], name: 'BBQ Masters', logo: "https://via.placeholder.com/300x300" },
    { id: 38, category_id: [4], name: 'Green Cuisine', logo: "https://via.placeholder.com/300x300" },
    { id: 39, category_id: [5], name: 'Wedding Grace', logo: "https://via.placeholder.com/300x300" },
    { id: 40, category_id: [1, 2], name: 'Cocktails & Roses', logo: "https://via.placeholder.com/300x300" },
    { id: 41, category_id: [3, 5], name: 'Gourmet Weddings', logo: "https://via.placeholder.com/300x300" },
    { id: 42, category_id: [2, 4], name: 'Petals & Provisions', logo: "https://via.placeholder.com/300x300" },
    { id: 43, category_id: [1, 5], name: 'Cheers Events', logo: "https://via.placeholder.com/300x300" },
    { id: 44, category_id: [4], name: 'Farm Fresh', logo: "https://via.placeholder.com/300x300" },
    { id: 45, category_id: [1, 2, 5], name: 'Rose & Drink', logo: "https://via.placeholder.com/300x300" },
    { id: 46, category_id: [3, 4], name: 'Protein Plate', logo: "https://via.placeholder.com/300x300" },
    { id: 47, category_id: [1, 3], name: 'Meaty Cocktails', logo: "https://via.placeholder.com/300x300" },
    { id: 48, category_id: [5], name: 'Golden Weddings', logo: "https://via.placeholder.com/300x300" },
    { id: 49, category_id: [2], name: 'Lily Lane', logo: "https://via.placeholder.com/300x300" },
    { id: 50, category_id: [4], name: 'Fresh Bites', logo: "https://via.placeholder.com/300x300" },
];

export let card=[]
// let storage = localStorage['cardLists']
// if(storage){
//     card  = JSON.parse(storage);
// }
